version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: storyweaver-postgres
    environment:
      POSTGRES_DB: storyweaver_demo
      POSTGRES_USER: storyweaver
      POSTGRES_PASSWORD: storyweaver_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storyweaver -d storyweaver_demo"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: storyweaver-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
